### ISSUE TITLE
SBIの作るメタバース団体は名称にメタバースは入っていないが追加するかどうか

### ISSUE THREAD

**Issue by ledyba** [neon-izm/metaverse_associations_jp#3]
> 巨大な仮想空間であるメタバースなどデジタル系の経済団体が乱立模様だ。[SBIホールディングス](https://www.nikkei.com/nkd/company/?scode=8473)（HD）がメタバースを含むデジタル空間の政策提言などを目的にした業界団体を4月にも設立する
> 
> SBIが準備する新団体名称は一般社団法人「日本デジタル空間経済連盟」
> 
> [「メタバース団体」、SBIも新設　ルール整備にらみ乱立: 日本経済新聞](https://www.nikkei.com/article/DGXZQOUB015OQ0R00C22A4000000/)

いかがいたしましょう？
個人的には「デジタル空間経済」は「メタバース」のほぼ同義語（含有するもの）として使われてるような感想は抱きました。
（とりあえず、実際に立つのを待ってから、ですかね…？）

**Comment by neon-izm** [comment]
無事設立されたら加えたいですね！

**Comment by ledyba** [comment]
無事設立されたそうです

「日本デジタル空間経済連盟」設立のお知らせ(SBIホールディングス)｜ニュースリリース｜SBIホールディングス
https://www.sbigroup.co.jp/news/2022/0415_12982.html

> 当面は、各業界から50社程度を会員として募り、9月末めどに提言を実施すべく、会員の方と議論を深めていきます。

だそうなので（うまくいけば）結構大規模になりそうですね

**Comment by ledyba** [comment]
あ、更新されてますね。ありがとうございます、closeします。
