### ISSUE TITLE
デジタル空間経済が記載可能であれば、バーチャルライツも載せていいのでは

### ISSUE THREAD

**Issue by KunitakeYuto** [neon-izm/metaverse_associations_jp#8]
以前PRの提案をさせていただいた際に、「メタバース」という単語が含まれているかどうかを判断材料としてはどうか(含まれていないものはフォークプロジェクトに記載してはどうか)という議論がありましたが、下記のissuesを拝見し基準に変更があったのかと思いましたので再度issuesを立てさせていただきます。

[SBIの作るメタバース団体は名称にメタバースは入っていないが追加するかどうか ](https://github.com/neon-izm/metaverse_associations_jp/issues/3)

NTTデータによる特集記事の[表：国内のメタバース関連団体（2022/5時点）](https://www.nttdata.com/jp/ja/data-insight/2022/0608/)にて関連団体がまとめられており、NPO法人バーチャルライツは、日本デジタル空間経済連盟やMetaverse Japan等と共に、関連団体として記載されています。

また、こちらのプレスリリース「[メタバースの文化振興に向けてNPO法人や文化団体が文化庁と意見交換](https://prtimes.jp/main/html/rd/p/000000010.000077712.html)」は行政側と調整した上で公開しておりますので、行政側からの認識としてもバーチャルライツがメタバース関連団体であることの証明になると思います。

前回のrequestから数ヶ月が経ち、当時の課題であった「メタバースの幅」についてコンセンサスが取れつつあると思いますので、再度のご検討のほどよろしくお願いいたします！

**Comment by neon-izm** [comment]
ありがとうございます。マージしました！
